/*
Nome: Donilo Jordão

*/

CREATE DATABASE ALUNOSPROJETOS;

USE ALUNOSPROJETOS;

CREATE TABLE   PROJETOS (
IDPROJETO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMEPROJETO VARCHAR(45) NOT NULL,
DESCRICAO VARCHAR(500)
);

CREATE TABLE   ALUNOS (
IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMEALUNO VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(11),
FKREPRESENTANTE INT,
FKPROJETOS INT NOT NULL,
FOREIGN KEY (FKREPRESENTANTE) REFERENCES ALUNOS (IDALUNO),
FOREIGN KEY (FKPROJETOS) REFERENCES PROJETOS (IDPROJETO)
);

CREATE TABLE   ACOMPANHANTES (
IDACOMPANHANTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMEACOMPANHANTE VARCHAR(45) NOT NULL,
RELACAO VARCHAR(45) NOT NULL,
FKALUNOS INT,
FOREIGN KEY (FKALUNOS) REFERENCES ALUNOS (IDALUNO)
);

INSERT INTO PROJETOS (NOMEPROJETO,DESCRICAO) VALUES
("BUSFACILITY", "PROJETO DE PI"),
("SITETAROT", "PROJETO INDIVIDUAL"), 
("CRUZADINHA", "PROJETO ARQUICOMP"),
("BATALHA NAVAL", "PROJETO BANCO DE DADOS");

INSERT INTO ALUNOS (NOMEALUNO,TELEFONE,FKREPRESENTANTE,FKPROJETOS) VALUES
("DONILO", "123456789", 1, 1),
("MATHEUS", "987654321", 2, 2),
("LUCAS", "987456321", 2, 3),
("PEDRO", "321654987", 1, 1),
("DIEGO", "789456123", 1, 1),
("DEREK", "456789123", 2, 4);

INSERT INTO ACOMPANHANTES (NOMEACOMPANHANTE,RELACAO,FKALUNOS) VALUES 
("JORGE", "MOTORISTA", 5),
("ZÉ", "AMIGO", 1), 
("ANA", "EX", 4),
("FERNANDO BRANDÃO", "PROFESSOR", 2);


SELECT * FROM PROJETOS;
SELECT * FROM ALUNOS;
SELECT * FROM ACOMPANHANTES;


SELECT ALUNOS.NOMEALUNO, PROJETOS.NOMEPROJETO, PROJETOS.DESCRICAO FROM ALUNOS
INNER JOIN PROJETOS 
ON ALUNOS.FKPROJETOS = PROJETOS.IDPROJETO;


SELECT ALUNOS.NOMEALUNO, ACOMPANHANTES.NOMEACOMPANHANTE, ACOMPANHANTES.RELACAO FROM ALUNOS
INNER JOIN ACOMPANHANTES 
ON ACOMPANHANTES.FKALUNOS = ALUNOS.IDALUNO;


SELECT ALUNOS.IDALUNO, ALUNOS.NOMEALUNO, ALUNOS.FKREPRESENTANTE FROM ALUNOS
INNER JOIN PROJETOS 
ON ALUNOS.FKREPRESENTANTE = ALUNOS.IDALUNO
GROUP BY ALUNOS.NOMEALUNO;


SELECT ALUNOS.NOMEALUNO, PROJETOS.NOMEPROJETO, PROJETOS.DESCRICAO FROM ALUNOS
INNER JOIN PROJETOS 
ON ALUNOS.FKPROJETOS = PROJETOS.IDPROJETO
WHERE NOMEPROJETO = "BUSFACILITY";


SELECT ALUNOS.NOMEALUNO, PROJETOS.NOMEPROJETO, PROJETOS.DESCRICAO, ACOMPANHANTES.NOMEACOMPANHANTE, ACOMPANHANTES.RELACAO FROM ALUNOS
INNER JOIN PROJETOS 
ON ALUNOS.FKPROJETOS = PROJETOS.IDPROJETO
INNER JOIN ACOMPANHANTES 
ON ACOMPANHANTES.FKALUNOS = ALUNOS.IDALUNO;