-- DONILO JORDÃO


CREATE DATABASE OLIMPIEADAS;

USE OLIMPIEADAS;

CREATE TABLE PAÍS (
ID_PAÍS INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
MEDALHAS_OURO INT,
MEDALHAS_PRATA INT,
MEDALHAS_BRONZE INT);

CREATE TABLE ATLETA (
ID_ATLETA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
GENERO CHAR(1),
IDADE INT,
NUM_MEDALHAS INT,
FK_PAÍS INT,
foreign key (FK_PAÍS) REFERENCES PAÍS(ID_PAÍS));

describe ATLETA;

INSERT INTO PAÍS (NOME, MEDALHAS_OURO, MEDALHAS_PRATA, MEDALHAS_BRONZE) VALUES
("BRAZIL",1,1,1),
("EUA",5,3,2),
("RUSSIA",10,3,2),
("INGLATERRA",5,4,4);

INSERT INTO ATLETA (NOME, GENERO, IDADE, NUM_MEDALHAS, FK_PAÍS) VALUES
("JOSUÉ","M",26,0,1),
("CAMPBELL","M",89,5,2),
("Елена","F",18,9,3),
("ANNE","F",21,1,4);

SELECT ATLETA.*, PAÍS.NOME, PAÍS.MEDALHAS_OURO
FROM ATLETA
INNER JOIN PAÍS 
ON PAÍS.ID_PAÍS = ATLETA.FK_PAÍS;

SELECT ATLETA.NOME, ATLETA.GENERO , PAÍS.NOME
FROM ATLETA
INNER JOIN PAÍS 
ON PAÍS.ID_PAÍS = ATLETA.FK_PAÍS;

USE OLIMPIEADAS;

CREATE TABLE MODALIDADE (
ID_MODALIDADE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
TIPO VARCHAR(60),
VARIACAO VARCHAR(50),
RECORDE_ATUAL INT,
FK_ATLETA INT,
FOREIGN KEY (FK_ATLETA) REFERENCES ATLETA(ID_ATLETA));

INSERT INTO MODALIDADE (NOME, TIPO, VARIACAO, RECORDE_ATUAL, FK_ATLETA)
VALUES
("NATAÇÃO","AQUÁTICO","NONE",50,4),
("FUTEBOL","CAMPO","FUTEBOL DE CAMPO",5,1),
("ESGRIMA","COMBATE","ESPADA",8,3),
("HIPISMO","COM ANIMAL","CAVALO",7,2);

SELECT MODALIDADE.*, ATLETA.*
FROM MODALIDADE
INNER JOIN ATLETA
ON ATLETA.ID_ATLETA = MODALIDADE.FK_ATLETA;

-- REGRA DE NEGÓCIO:
-- UM PARA MUITOS


