CREATE DATABASE FAMILIA;

USE FAMILIA;

CREATE TABLE AVO (
ID_AVO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
IDADE INT);

CREATE TABLE PAI (
ID_PAI INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
IDADE INT,
FK_AVO INT,
FOREIGN KEY(FK_AVO) REFERENCES AVO(ID_AVO));

CREATE TABLE FILHO (
ID_FILHO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
IDADE INT, 
FK_PAI INT,
FK_AVO INT,
FOREIGN KEY (FK_PAI) REFERENCES PAI(ID_PAI),  -- UM PRA MUITOS
FOREIGN KEY (FK_AVO) REFERENCES AVO(ID_AVO)); -- MUITOS PRA MUITOS

INSERT INTO AVO (NOME, IDADE) VALUES
("JOAQUIM",80), 
("ULISSES",76),
("GILMAR",78);

INSERT INTO PAI (NOME, IDADE, FK_AVO) VALUES
("PAULO",38,3),
("THIAGO",29,2),
("LEO",19,1);

INSERT INTO FILHO (NOME, IDADE, FK_PAI, FK_AVO) VALUES
("ENZO",2,3,1),
("BILLY",14,1,3),
("CASTIEL",9,2,2);

SELECT AVO.NOME , PAI.NOME
FROM PAI
INNER JOIN AVO
ON AVO.ID_AVO = PAI.FK_AVO;









