/*
NOME: DONILO JORDÃO
RA: 01212008
*/

# PRIMEIRA PARTE

CREATE DATABASE ATLETA;

USE ATLETA;

CREATE TABLE ATLETA (
IDATLETA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(40),
MODALIDADE VARCHAR(40),
QTDMEDALHAS INT);

INSERT INTO ATLETA (NOME, MODALIDADE, QTDMEDALHAS) VALUES
("ALMIR","NATAÇÃO",2),
("REBECA","VOLEI",0),
("GUSTAVO","BASQUETE",3),
("TIFANNY","NATAÇÃO",1),
("WILSON","BASQUETE",0),
("LIZANDRA","VOLEI",1),
("PEDRO","KARATÊ",0),
("CAMILA","XADREZ",8),
("JEFERSON","KARATÊ",1),
("IASMIN","XADREZ",1);

SELECT * FROM ATLETA;

SELECT NOME, QTDMEDALHAS FROM ATLETA;

SELECT * FROM ATLETA
WHERE MODALIDADE = "XADREZ";

SELECT * FROM ATLETA
ORDER BY MODALIDADE;

SELECT * FROM ATLETA
ORDER BY QTDMEDALHAS DESC;

SELECT * FROM ATLETA
WHERE NOME LIKE "%S%";

SELECT * FROM ATLETA
WHERE NOME LIKE "A%";

SELECT * FROM ATLETA
WHERE NOME LIKE "%O";

SELECT * FROM ATLETA
WHERE NOME LIKE "%R_";

DROP TABLE ATLETA;

# SEGUNDA PARTE

CREATE DATABASE MUSICA;

USE MUSICA;

CREATE TABLE MUSICA (
IDMUSICA INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(40),
ARTISTA VARCHAR(40),
GENERO VARCHAR(40));

INSERT INTO MUSICA (TITULO, ARTISTA, GENERO) VALUES
("MOSCA NA SOPA","RAUL SEIXAS","MPB"),
("EU NASCI A DEZ MIL ANOS","RAUL SEIXAS","MPB"),
("PET SEMATARY","RAMONES","ROCK"),
("JUDY IS A PUNK","RAMONES","ROCK"),
("I WANT TO BREAK FREE","QUEEN","ROCK"),
("DON'T STOP ME NOW","QUEEN","ROCK"),
("CEROL NA MÃO","BONDE DO TIGRÃO","FUNK"),
("TAPINHA","BONDE DO TIGRÃO","FUNK"),
("WANNABE","SPICE GIRLS","POP"),
("VIVA FOREVER","SPICE GIRLS","POP");

SELECT * FROM MUSICA;

SELECT TITULO, ARTISTA FROM MUSICA;

SELECT * FROM MUSICA
WHERE GENERO = "POP";

SELECT * FROM MUSICA
WHERE ARTISTA = "QUEEN";

SELECT *  FROM MUSICA
ORDER BY TITULO;

SELECT * FROM MUSICA
ORDER BY ARTISTA DESC;

SELECT * FROM MUSICA
WHERE TITULO LIKE "I%";

SELECT * FROM MUSICA
WHERE ARTISTA LIKE "%S";

SELECT * FROM MUSICA
WHERE GENERO LIKE "_O%";

SELECT * FROM MUSICA
WHERE TITULO LIKE "%P_";

DROP TABLE MUSICA;


