CREATE DATABASE CURSO;

USE CURSO;

CREATE TABLE RESPONSAVEL_FINANCEIRO (
IDRESPONSAVELFINANCEIRO INT PRIMARY KEY AUTO_INCREMENT,
NOMERESPONSAVEL VARCHAR(45),
RELACAORESPONSAVEL VARCHAR(45));

CREATE TABLE ALUNO (
IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(45),
INDICAÇÃO INT,
FK_RESPONSAVELFINANCEIRO INT,
FOREIGN KEY(FK_RESPONSAVELFINANCEIRO) REFERENCES RESPONSAVEL_FINANCEIRO(IDRESPONSAVELFINANCEIRO),
FOREIGN KEY(INDICAÇÃO)REFERENCES ALUNO(IDALUNO));

CREATE TABLE CURSO (
IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
NOMECURSO VARCHAR(45));

CREATE TABLE MATRICULA (
IDMATRICULA INT,
FKALUNO INT,
FKCURSO INT,
DATAMATRICULA DATE,
PRECOMATRICULA DECIMAL(10,2),
FOREIGN KEY(FKALUNO) REFERENCES ALUNO(IDALUNO),
FOREIGN KEY(FKCURSO) REFERENCES CURSO(IDCURSO));

INSERT INTO RESPONSAVEL_FINANCEIRO (NOMERESPONSAVEL, RELACAORESPONSAVEL) VALUES
("MARIA","MÃE"),
("JORGE","PAI"),
("ALAN","IRMÃO");

INSERT INTO ALUNO (NOME, INDICAÇÃO, FK_RESPONSAVELFINANCEIRO) VALUES
("PEDRO",NULL,1),
("ANA",1,1),
("CASSANDRA",NULL,2),
("GUSTAVO",3,3),
("GUILHERME",3,2),
("REBECCA",NULL,1);

INSERT INTO CURSO (NOMECURSO) VALUES
("NATAÇÃO"),
("XADREZ"),
("ESGRIMA"),
("KARATÊ"),
("PENTEST"),
("VIOLINO");

INSERT INTO MATRICULA (FKALUNO,FKCURSO,DATAMATRICULA) VALUES
(1,3,'2021-10-10'),
(3,2,'2021-09-16'),
(2,4,'2021-09-22'),
(2,2,'2020-04-02'),
(4,6,'2021-03-29'),
(4,5,'2021-02-05'),
(5,1,'2019-10-10'),
(5,2,'2020-03-26'),
(5,3,'2021-06-09'),
(6,5,'2019-04-13'),
(6,5,'2021-05-10');

SELECT ALUNO.NOME, CURSO.NOMECURSO, MATRICULA.DATAMATRICULA FROM MATRICULA
JOIN ALUNO ON ALUNO.IDALUNO = MATRICULA.FKALUNO
JOIN CURSO ON CURSO.IDCURSO = MATRICULA.FKCURSO
WHERE MATRICULA.DATAMATRICULA ;