package br.com.sptech.totemsistem;

import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.lang.Thread;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;

/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin2
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        inputEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 58, 147));

        jLabel1.setBackground(new java.awt.Color(54, 58, 147));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Totem System");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha:");

        inputSenha.setBackground(new java.awt.Color(0, 29, 62));
        inputSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        inputEmail.setBackground(new java.awt.Color(0, 29, 62));
        inputEmail.setForeground(new java.awt.Color(255, 255, 255));
        inputEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconTotemSystem-Circulo.png"))); // NOI18N

        btnEntrar.setBackground(new java.awt.Color(93, 95, 239));
        btnEntrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        Usuario user = new Usuario();
        ValidacaoLogin validacao = new ValidacaoLogin();
        Scanner leitor = new Scanner(System.in);
        SalvarDados salvar = new SalvarDados();
        BancoDeDados banco = new BancoDeDados();
        Sistema sistema = new Sistema();
        JSONObject json = new JSONObject();

        ValidacaoLogin validacaoBanco = new ValidacaoLogin();
        String email = inputEmail.getText();
        String senha = inputSenha.getText();

        Boolean validacaoCampo = user.validacaoCampo(email, senha);

        if (validacaoCampo == true) {
            // Boolean validacaoBanco = user.validarCredenciais(email, senha);
            if (validacaoBanco.validarLogin(email, senha)) {

                JOptionPane.showMessageDialog(rootPane, "Usuário logado com sucesso!!!");
                try {
                    sistema.logAcao("---> Usuário "+email+" acessou o totem");
                } catch (IOException ex) {
                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    this.validacoesTotem();
                } catch (Exception e) {
                    System.out.println(e);
                    try {
                        sistema.logErro("---> Erro na conexão com o banco");
                    } catch (IOException ex) {
                        Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        } else {
            //System.out.println(username);
            System.out.println("Dados incorretos!!!!!");
            JOptionPane.showMessageDialog(rootPane, "Email ou senha inválidos!");
            try {
                sistema.logAcao("---> tentativa de login com email: "+email);
                //System.out.println(username + "test");
            } catch (IOException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void menu() throws IOException {

        Sistema sistema = new Sistema();
        Scanner leitor = new Scanner(System.in);
        Info info = new Info();
        Totem totem = new Totem();
        SalvarDados salvar = new SalvarDados();

        Integer opcao = 0;

        while (opcao <= 5) {

            sistema.setLinhas("=", 20);
            System.out.println("\nBEM VINDO À TOTEM SYSTEM\n");
            System.out.println("Escolha uma opção:"
                    + "\n1 - Mostrar informações do Totem."
                    + "\n2 - Mostrar processos do Totem."
                    + "\n3 - Mostrar serviços em Execução."
                    + "\n4 - Salvar dados de máquina."
                    + "\n5 - Salvar dados variáveis."
                    + "\n6 - Sair.");
            opcao = leitor.nextInt();

            switch (opcao) {

                case 1:
                    System.out.println("\nOpção escolhida: Informações do Totem\n");
                    info.getInfo();
                    sistema.logAcao("---> Usuario visualizou informações do Totem");
                    System.out.println("\nFim.");
                    break;
                case 2:
                    System.out.println("\nOpção escolhida: Mostrar processos do Totem.\n");
                    totem.processos();
                    sistema.logAcao("---> Usuario visualizou processos do totem");
                    System.out.println("\nFim.");
                    break;
                case 3:
                    System.out.println("\nOpção escolhida: Mostrar serviços em Execução.\n");
                    totem.servicos();
                    sistema.logAcao("---> Usuario visualizou serviços do totem");
                    System.out.println("\nFim.");
                    break;
                case 4:
                    System.out.println("\nOpção escolhida: Salvar dados estáticos.\n");
                    System.out.println("\nSalvando dados...");
                    salvar.salvarDadosEstaticos();
                    sistema.logAcao("---> Usuario salvou dados estáticos do Totem");
                    System.out.println("\nFim.");
                    break;
                case 5:
                    System.out.println("\nOpção escolhida: Salvar dados variáveis.");
                    sistema.logAcao("---> Usuario salvou dados variáveis do Totem");
                    System.out.println("\nSalvando dados...");

                    try {
                        for (int i = 0; i < 600; i++) {

                            salvar.salvarDadosVariaveis();
                            Thread.sleep(2000);

                        }
                    } catch (Exception e) {
                        System.out.println("ERRO");
                    }
                    System.out.println("\nFim.");
                    break;
                case 6:
                    System.out.println("Saindo... até logo!");
                    sistema.logAcao("---> Usuario deslogou do sistema");
                    break;

                default:
                    System.out.println("\nOpção Inválida.\n");
                    sistema.logAcao("---> Usuario digitou opção inválida");
                    break;
            }

        }
    }

    public void validacoesTotem() throws SQLException, ClassNotFoundException, IOException {

        Usuario user = new Usuario();
        ValidacaoLogin validacao = new ValidacaoLogin();
        Scanner leitor = new Scanner(System.in);
        SalvarDados salvar = new SalvarDados();
        BancoDeDados banco = new BancoDeDados();
        Sistema sistema = new Sistema();

        
        if (banco.existeHostname("azure") && banco.existeHostname("mysql")) {

            this.menu();

        } else if(!banco.existeHostname("azure") || !banco.existeHostname("mysql")){
            System.out.println("\nERRO! Totem não cadastrado!");
            sistema.logErro("---> Erro! Totem não cadastrado!");
            System.out.println("Deseja cadastrar este Totem minimamente? (S/N)");
            String resposta = leitor.nextLine();
            if (resposta.toLowerCase().equals("s")) {
                sistema.logAcao("---> Cadastro de novo totem escolhido");
                System.out.println("\nDigite o nome da estação onde deseja cadastrar o Totem:");
                String estacao = leitor.nextLine();

                    salvar.salvarTotemTemporariamente(estacao);
                    sistema.logAcao("---> Novo totem salvo na estação: "+estacao);
                    this.menu();

            } else if (resposta.equals("N")) {
                sistema.logAcao("---> Usuario não cadastrou novo totem");
                System.out.println("Fim do Programa!");
            } else {
                sistema.logErro("---> Erro! Usuario digitou valor incorreto");
                System.out.println("Valor incorreto");
            }
        }

    }
}
